const contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  { name: "contract_type", type: "number", required: false },
  { name: "number", type: "number", required: false },
];
const contract_commission = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "commission_percentage", type: "number", required: false },
  { name: "commission_value", type: "number", required: false },
  {
    name: "commission_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "commission_account",
    ref_col: "id",
  },
  { name: "commission_note", type: "text", required: false },
  { name: "commission_from_owner_percentage", type: "number", required: false },
  {
    name: "    commission_from_owner_value double precision null,",
    type: "number",
    required: false,
  },
  {
    name: "commission_from_owner_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "commission_from_owner_account",
    ref_col: "id",
  },
  { name: "commission_from_owner_note", type: "text", required: false },
  {
    name: "commission_from_lessor_percentage",
    type: "number",
    required: false,
  },
  // { name: "commission_from_lessor_value", type: "number", required: false },
  // {
  //   name: "commission_from_lessor_account_id",
  //   type: "uuid",
  //   required: false,
  //   is_ref: true,
  //   ref_table: "commission_from_lessor_account",
  //   ref_col: "id",
  // },
  // { name: "commission_from_lessor_note", type: "text", required: false },
];
const contract_cycle = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "contract_documented",
    type: "boolean",
    required: false,
    key: "switch",
  },
  {
    name: "contract_certifying",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "contract_certifying_body", type: "text", required: false },
  {
    name: "contract_received",
    type: "boolean",
    required: false,
    key: "switch",
  },
  {
    name: "contract_delivered",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "contract_signed", type: "boolean", required: false, key: "switch" },
  { name: "municipal_license_num", type: "number", required: false },
  { name: "municipal_license_from", type: "date", required: false },
  { name: "municipal_license_to", type: "date", required: false },
  { name: "license_num", type: "number", required: false },
  { name: "license_from", type: "date", required: false },
  { name: "license_to", type: "date", required: false },
  { name: "civil_license_num", type: "number", required: false },
  { name: "civil_license_from", type: "date", required: false },
  { name: "civil_license_to", type: "date", required: false },
];
const contract_terms = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "contract_terms", type: "text", required: false },
];
const contract_linked_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "main_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "main_contract",
    ref_col: "id",
  },
];
const contract_pictures = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "picture", type: "text", required: false },
];
const contract_termination = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "termination_date", type: "date", required: false },
  { name: "owner_total_amount", type: "number", required: false },
  { name: "new_amount", type: "number", required: false },
  { name: "round_to", type: "number", required: false },
  { name: "revenue_note", type: "text", required: false },
  { name: "fines", type: "text", required: false },
  {
    name: "fines_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "fines_revenue_account",
    ref_col: "id",
  },
  { name: "fine_note", type: "text", required: false },
  {
    name: "evacuation_request",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "evacuation_date", type: "date", required: false },
  {
    name: "clearance_printed",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "clearance_printed_date", type: "date", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
];

const contract_receipt_number = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "receipt_number", type: "number", required: false },
  { name: "receipt_date", type: "date", required: false },
  { name: "receipt_statement", type: "text", required: false },
];

const contract_other_fees = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "date", type: "date", required: false },
  { name: "fee_amount", type: "number", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "notes", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
];

const contract_fee = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
  { name: "entrynumber", type: "number", required: false },
  { name: "create_entry", type: "boolean", required: false, key: "switch" },
];
const contract_fixed_assets = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "assets_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "assets",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
];

const contract_payments = [];

const contract_rent_financial = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "contract_type", type: "number", required: false },
  { name: "contract_value", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "final_price", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "electricity_deposit", type: "number", required: false },
  { name: "electricity_last_meter_reading", type: "number", required: false },
  { name: "contract_duration", type: "text", required: false },
  { name: "start_duration_date", type: "date", required: false },
  { name: "end_duration_date", type: "date", required: false },
  { name: "paid_type", type: "number", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
  {
    name: "fee_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
];
const contract_rent_financial_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "contract_type", type: "number", required: false },
  { name: "contract_value", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "final_price", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "contract_duration", type: "text", required: false },
  { name: "start_duration_date", type: "date", required: false },
  { name: "end_duration_date", type: "date", required: false },
  { name: "paid_type", type: "number", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
];

const contract_sale_financial = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "amount", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "discount_contract_amount", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "electricity_deposit", type: "number", required: false },
  { name: "electricity_last_meter_reading", type: "number", required: false },
  { name: "paid_type", type: "number", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
  {
    name: "fee_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
];
const contract_sale_financial_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "paid_type", type: "number", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "amount", type: "number", required: false },
  { name: "discount_contract_amount", type: "number", required: false },
  { name: "date", type: "date", required: false },
];

// Contract Differences
// == Contract Sale
//  === Apartment
const apartment_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "residents_count", type: "number", required: false },
  { name: "property_area", type: "number", required: false },
];

//  === parking
const parking_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "parking", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phone", type: "number", required: false },
  { name: "status", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "car_plate_no", type: "varchar", required: false },
  { name: "card_no", type: "varchar", required: false },
  { name: "car_color", type: "varchar", required: false },
  { name: "car_type", type: "varchar", required: false },
  { name: "related_contract", type: "uuid", required: false }, // unknown table
];

//  === Shop
const shop_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "property_area", type: "number", required: false },
];

//  === land
const land_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "land_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "land", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "status", type: "text", required: false },
  { name: "issue_date", type: "date", required: false },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
];

// == Contract Rent
//  === Apartment
const apartment_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "status", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "residents_count", type: "number", required: false },
  { name: "property_area", type: "number", required: false },
  { name: "purpose_rental", type: "text", required: false },
  { name: "rental_period_text", type: "text", required: false },
  { name: "rent_type", type: "number", required: false },
  { name: "payment_text", type: "text", required: false },
  { name: "contracts_number_prev", type: "number", required: false },
  { name: "contracts_number_current", type: "number", required: false },
];
//  === parking
const parking_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "parking",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phone", type: "number", required: false },
  { name: "status", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "rental_period_text", type: "text", required: false },
  { name: "rent_type", type: "number", required: false },
  { name: "payment_text", type: "text", required: false },
  { name: "car_plate_no", type: "varchar", required: false },
  { name: "card_no", type: "varchar", required: false },
  { name: "car_color", type: "varchar", required: false },
  { name: "car_type", type: "varchar", required: false },
  { name: "related_contract", type: "uuid", required: false },
];

//  === Shop
const shop_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: false },
  { name: "nationality", type: "number", required: false },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "status", type: "number", required: false },
  { name: "issue_date", type: "date", required: false },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  { name: "property_area", type: "number", required: false },
  { name: "purpose_rental", type: "text", required: false },
  { name: "rental_period_text", type: "text", required: false },
  { name: "rent_type", type: "number", required: false },
  { name: "payment_text", type: "text", required: false },
  { name: "contracts_number_prev", type: "number", required: false },
  { name: "contracts_number_current", type: "number", required: false },
];

// contract rent
const apartment_rent_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "fixed_assets",
    "linked_parking",
    "contract_cycle",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: apartment_rent_contract },
    financial: { fields: contract_rent_financial },
    // payments: {}{fields :    // payments},
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    fixed_assets: { fields: contract_fixed_assets, formType: "grid" },
    linked_parking: { fields: contract_linked_parking, formType: "grid" },
    contract_cycle: { fields: contract_cycle },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

const shop_rent_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "fixed_assets",
    "linked_parking",
    "contract_cycle",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: shop_rent_contract },
    financial: { fields: contract_rent_financial },
    // payments
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    fixed_assets: { fields: contract_fixed_assets, formType: "grid" },
    linked_parking: { fields: contract_linked_parking, formType: "grid" },
    contract_cycle: { fields: contract_cycle },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

const parking_rent_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: parking_rent_contract },
    financial: { fields: contract_rent_financial_parking },
    // payments
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

// Sale contract

const apartment_sale_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "fixed_assets",
    "linked_parking",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: apartment_sale_contract },
    financial: { fields: contract_sale_financial },
    // payments
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    fixed_assets: { fields: contract_fixed_assets, formType: "grid" },
    linked_parking: { fields: contract_linked_parking, formType: "grid" },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

const shop_sale_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "fixed_assets",
    "linked_parking",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: shop_sale_contract },
    financial: { fields: contract_sale_financial },
    // payments: { fields },
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    fixed_assets: { fields: contract_fixed_assets, formType: "grid" },
    linked_parking: { fields: contract_linked_parking, formType: "grid" },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

const parking_sale_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: parking_sale_contract },
    financial: { fields: contract_sale_financial_parking },
    // payments: {{fields:     // payments}},
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

const land_sale_contract_group = {
  steps: [
    "general",
    "financial",
    // "payments",
    "commission",
    "terms",
    "pictures",
    "other_fees",
    "fixed_assets",
    "linked_parking",
    "termination",
    "recipes_numbers",
  ],
  forms: {
    general: { fields: land_sale_contract },
    financial: { fields: contract_sale_financial },
    // payments
    commission: { fields: contract_commission },
    terms: { fields: contract_terms },
    pictures: { fields: contract_pictures, formType: "gallery" },
    other_fees: { fields: contract_other_fees, formType: "grid" },
    fixed_assets: { fields: contract_fixed_assets, formType: "grid" },
    linked_parking: { fields: contract_linked_parking, formType: "grid" },
    termination: { fields: contract_termination },
    recipes_numbers: { fields: contract_receipt_number, formType: "grid" },
  },
};

export const CONTRACTS_FORM = {
  apartment_rent_contract: apartment_rent_contract_group,
  shop_rent_contract: shop_rent_contract_group,
  parking_rent_contract: parking_rent_contract_group,
  apartment_sale_contract: apartment_sale_contract_group,
  shop_sale_contract: shop_sale_contract_group,
  parking_sale_contract: parking_sale_contract_group,
  land_sale_contract: land_sale_contract_group,
};
