import {
  ACTIONS,
  APARTMENT_STEPS_CONTRACT,
  LAND_STEPS_CONTRACT,
  PARKING_STEPS_CONTRACT,
  SELECT_LISTS,
  SHOP_STEPS_CONTRACT,
} from "Helpers/constants";
import { validate } from "uuid";

const contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_type"),
  },
  {
    name: "flat_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contact_pattern_assets_type"),
    // future  add land to flat type list  -> contact_pattern_assets_type
  },
  { name: "number", type: "number", required: true, hide_in_form: true },
];

const contract_commission = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "commission_percentage", type: "number", required: false },
  { name: "commission_value", type: "number", required: false },
  {
    name: "commission_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_note", type: "text", required: false },
  { name: "commission_from_owner_percentage", type: "number", required: false },
  {
    name: "commission_from_owner_value",
    type: "number",
    required: false,
  },
  {
    name: "commission_from_owner_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_owner_note", type: "text", required: false },
  {
    name: "commission_from_lessor_percentage",
    type: "number",
    required: false,
  },
  // { name: "commission_from_lessor_value", type: "number", required: false },
  // {
  //   name: "commission_from_lessor_account_id",
  //   type: "uuid",
  //   required: false,
  //   is_ref: true,
  //   ref_table: "commission_from_lessor_account",
  //   ref_col: "id",
  // },
  // { name: "commission_from_lessor_note", type: "text", required: false },
];
const contract_cycle = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "contract_documented",
    type: "boolean",
    required: false,
    key: "switch",
  },
  {
    name: "contract_certifying",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "contract_certifying_body", type: "text", required: false },
  {
    name: "contract_received",
    type: "boolean",
    required: false,
    key: "switch",
  },
  {
    name: "contract_delivered",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "contract_signed", type: "boolean", required: false, key: "switch" },
  { name: "municipal_license_num", type: "number", required: false },
  { name: "municipal_license_from", type: "date", required: false },
  { name: "municipal_license_to", type: "date", required: false },
  { name: "license_num", type: "number", required: false },
  { name: "license_from", type: "date", required: false },
  { name: "license_to", type: "date", required: false },
  { name: "civil_license_num", type: "number", required: false },
  { name: "civil_license_from", type: "date", required: false },
  { name: "civil_license_to", type: "date", required: false },
];
const contract_terms = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "contract_terms", type: "text", required: false },
];

const contract_linked_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "main_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
];

const contract_pictures = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "picture",
    type: "file",
    key: "image",
    multiple: true,
    required: false,
  },
];
const contract_termination = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "termination_date", type: "date", required: false },
  { name: "owner_total_amount", type: "number", required: false },
  { name: "new_amount", type: "number", required: false },
  {
    name: "round_to",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_round_to"),
  },
  { name: "revenue_note", type: "text", required: false },
  { name: "fines", type: "text", required: false },
  {
    name: "fines_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "fine_note", type: "text", required: false },
  {
    name: "evacuation_request",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "evacuation_date", type: "date", required: false },
  {
    name: "clearance_printed",
    type: "boolean",
    required: false,
    key: "switch",
  },
  { name: "clearance_printed_date", type: "date", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "btn_action",
    action: ACTIONS.OPEN_TERMINATION_FINES_FORM,
    label: "Open Terminations fines",
    onClick: () => {},
  },
];

const termination_fines_grid = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "date", required: false },
  {
    name: "contract_termination_fines_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract_termination_fines",
    ref_col: "id",
    hide_in_form: true

  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "fee_amount", type: "float4", required: false },
  { name: "notes", type: "text", required: false },
];
const contract_receipt_number = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "receipt_number", type: "number", required: false },
  { name: "receipt_date", type: "date", required: false },
  { name: "receipt_statement", type: "text", required: false },
];

const contract_other_fees = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "date", type: "date", required: false },
  { name: "fee_amount", type: "number", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "notes", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
];

const contract_fixed_assets = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "created_at",
    type: "date",
    required: false,
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "assets_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "assets",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
];

const rent_contract_financial = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "bank",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "bank",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "contract_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_type"),
  },
  { name: "contract_value", type: "number", required: true },
  { name: "monthly_value", type: "number", required: true },
  {
    name: "currency_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: true },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "final_price", type: "number", required: true },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "electricity_deposit", type: "number", required: false },
  { name: "electricity_last_meter_reading", type: "number", required: false },
  {
    name: "contract_duration",

    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_duration"),
    allowInsert: true,
  },
  {
    name: "start_duration_date",
    type: "date",
    required: true,
    watch: "contract_duration",
    defaultValue: new Date(),
    condition: 4,
  },
  {
    name: "end_duration_date",
    type: "date",
    required: true,
    watch: "contract_duration",
    condition: 4,
    defaultValue: new Date(new Date().getMonth() + 1),
  },
  {
    name: "paid_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_paid_type"),
    allowInsert: true,
  },
  {
    name: "btn_action",
    action: ACTIONS.OPEN_INSTALLMENT_FORM,
    label: "Open Installment panel",
    onClick: () => {},
    condition: 4,
    watch: "paid_type",
  },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
  {
    name: "fee_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "gen_entries",
    type: "boolean",
    required: false,
    key: "switch",
  },
];
const contract_rent_financial_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "contract_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_type"),
  },
  { name: "contract_value", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "final_price", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  {
    name: "contract_duration",

    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_duration"),
    allowInsert: true,
  },
  {
    name: "start_duration_date",
    type: "date",
    required: false,
    watch: "contract_duration",
    condition: 4,
  },
  {
    name: "end_duration_date",
    type: "date",
    required: false,
    watch: "contract_duration",
    condition: 4,
  },
  {
    name: "paid_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_paid_type"),
    allowInsert: true,
  },
  {
    name: "btn_action",
    action: ACTIONS.OPEN_INSTALLMENT_FORM,
    label: "Open Installment panel",
    condition: 4,
    watch: "paid_type",
  },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
  {
    name: "gen_entries",
    type: "boolean",
    required: false,
    key: "switch",
  },
];

const contract_sale_financial = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "amount", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  { name: "discount_contract_amount", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  { name: "electricity_deposit", type: "number", required: false },
  { name: "electricity_last_meter_reading", type: "number", required: false },
  {
    name: "paid_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_paid_type"),
    allowInsert: true,
  },
  {
    name: "btn_action",
    action: ACTIONS.OPEN_INSTALLMENT_FORM,
    label: "Open Installment panel",
    onClick: () => {},
    condition: 4,
    watch: "paid_type",
  },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fees", type: "text", required: false },
  {
    name: "fee_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  {
    name: "gen_entries",
    type: "boolean",
    required: false,
    key: "switch",
  },
];

const contract_sale_financial_parking = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_rate", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "previous_securing", type: "number", required: false },
  { name: "current_securing_percentage", type: "number", required: false },
  { name: "current_securing_value", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "contract_registration_price", type: "number", required: false },
  {
    name: "paid_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_paid_type"),
    allowInsert: true,
  },
  {
    name: "btn_action",
    action: ACTIONS.OPEN_INSTALLMENT_FORM,
    label: "Open Installment panel",
    onClick: () => {},
    condition: 4,
    watch: "paid_type",
  },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "contract_registration_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "amount", type: "number", required: false },
  { name: "discount_contract_amount", type: "number", required: false },
  { name: "date", type: "date", required: false },
  {
    name: "gen_entries",
    type: "boolean",
    required: false,
    key: "switch",
  },
];

// Contract Differences
// == Contract Sale
//  === Apartment
const apartment_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "apartment", // unknown table
    ref_col: "id",
    ref_name: "apartment_no",
  },
  { name: "description", type: "text", required: false },

  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },

  { name: "residents_count", type: "number", required: false },
  {
    name: "property_area",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("flat_property_type"),
  },
];

//  === parking
const parking_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "parking", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },

  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phone", type: "number", required: false },
  {
    name: "status",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_status"),
  },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },

  { name: "car_plate_no", type: "varchar", required: false },
  { name: "card_no", type: "varchar", required: false },
  { name: "car_color", type: "varchar", required: false },
  { name: "car_type", type: "varchar", required: false },
  { name: "related_contract", type: "uuid", required: false }, // unknown table
];

//  === Shop
const shop_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "shop_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "shop", // unknown table
    ref_col: "id",
    ref_name: "shop_no",
  },
  { name: "description", type: "text", required: false },

  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },

  {
    name: "property_area",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("flat_property_type"),
  },
];

//  === land
const land_sale_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "land_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "land", // unknown table
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  { name: "status", type: "text", required: false },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },
];

// == Contract Rent
//  === Apartment
const apartment_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "apartment_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "apartment",
    ref_col: "id",
    ref_name: "apartment_no",
  },
  { name: "description", type: "text", required: false },

  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  {
    name: "status",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_status"),
  },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },

  { name: "residents_count", type: "number", required: false },
  {
    name: "property_area",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("flat_property_type"),
  },
  { name: "purpose_rental", type: "text", required: false },
  { name: "rental_period_text", type: "text", required: false },
  {
    name: "rent_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_contract_type"),
  },
  { name: "payment_text", type: "text", required: false },
  { name: "contracts_number_prev", type: "number", required: false },
  { name: "contracts_number_current", type: "number", required: false },
];
//  === parking
const parking_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "parking",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },

  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },
  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phone", type: "number", required: false },
  {
    name: "status",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_status"),
  },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },

  { name: "rental_period_text", type: "text", required: false },
  {
    name: "rent_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_contract_type"),
  },
  { name: "payment_text", type: "text", required: false },
  { name: "car_plate_no", type: "varchar", required: false },
  { name: "card_no", type: "varchar", required: false },
  { name: "car_color", type: "varchar", required: false },
  { name: "car_type", type: "varchar", required: false },
  { name: "related_contract", type: "uuid", required: false },
];

//  === Shop
const shop_rent_contract = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  { name: "feedback", type: "boolean", required: false, key: "switch" },
  { name: "lawsuit", type: "boolean", required: false, key: "switch" },
  {
    name: "client_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "shop_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "shop",
    ref_col: "id",
    ref_name: "shop_no",
  },
  { name: "description", type: "text", required: false },

  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
    ref_name: "full_name",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: true,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
    ref_name: "full_name",
  },
  { name: "ownership", type: "text", required: false },

  {
    name: "nationality",
    required: false,
    key: "select",
    intValue: true,
    list: SELECT_LISTS("nationality_list"),
  },
  { name: "work_phone", type: "number", required: false },
  { name: "phono", type: "number", required: false },
  {
    name: "status",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("contract_status"),
  },
  { name: "property_delivery_date", type: "date", required: true },
  { name: "issue_date", type: "date", required: true },
  { name: "contract_location", type: "text", required: false },
  { name: "commercial_name", type: "text", required: false },

  {
    name: "property_area",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("flat_property_type"),
  },
  { name: "purpose_rental", type: "text", required: false },
  { name: "rental_period_text", type: "text", required: false },
  {
    name: "rent_type",
    key: "select",
    required: true,
    intValue: true,
    list: SELECT_LISTS("rent_contract_type"),
  },
  { name: "payment_text", type: "text", required: false },
  { name: "contracts_number_prev", type: "number", required: false },
  { name: "contracts_number_current", type: "number", required: false },
];

// contract rent
const apartment_rent_contract_group = {
  forms: {
    [APARTMENT_STEPS_CONTRACT.apartment_contract_general]: {
      fields: apartment_rent_contract,
      tab_name: "apartment_rent_contract",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_financial]: {
      fields: rent_contract_financial,
      tab_name: "contract_rent_financial",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_commission]: {
      fields: contract_commission,
      tab_name: "contract_commission",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_terms]: {
      fields: contract_terms,
      tab_name: "contract_terms",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_fixed_assets]: {
      fields: contract_fixed_assets,
      tab_name: "contract_fixed_assets",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_linked_parking]: {
      fields: contract_linked_parking,
      tab_name: "contract_linked_parking",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_rent_contract_cycle]: {
      fields: contract_cycle,
      tab_name: "contract_cycle",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

const shop_rent_contract_group = {
  forms: {
    [SHOP_STEPS_CONTRACT.shop_contract_general]: {
      fields: shop_rent_contract,
      tab_name: "shop_rent_contract",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_financial]: {
      fields: rent_contract_financial,
      tab_name: "contract_rent_financial",
    },
    // payments
    [SHOP_STEPS_CONTRACT.shop_contract_commission]: {
      fields: contract_commission,
      tab_name: "contract_commission",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_terms]: { fields: contract_terms },
    [SHOP_STEPS_CONTRACT.shop_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_fixed_assets]: {
      fields: contract_fixed_assets,
      tab_name: "contract_fixed_assets",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_linked_parking]: {
      fields: contract_linked_parking,
      tab_name: "contract_linked_parking",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_rent_contract_cycle]: {
      fields: contract_cycle,
      tab_name: "contract_cycle",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

const parking_rent_contract_group = {
  forms: {
    [PARKING_STEPS_CONTRACT.parking_contract_general]: {
      fields: parking_rent_contract,
      tab_name: "parking_rent_contract",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_financial]: {
      fields: contract_rent_financial_parking,
      tab_name: "contract_rent_financial_parking",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_commission]: {
      fields: contract_commission,
      tab_name: "contract_commission",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_terms]: {
      fields: contract_terms,
      tab_name: "contract_terms",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

// Sale contract

const apartment_sale_contract_group = {
  forms: {
    [APARTMENT_STEPS_CONTRACT.apartment_contract_general]: {
      fields: apartment_sale_contract,
      tab_name: "apartment_sale_contract",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_financial]: {
      fields: contract_sale_financial,
      tab_name: "contract_sale_financial",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_commission]: {
      fields: contract_commission,
      tab_name: "contract_commission",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_terms]: {
      fields: contract_terms,
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_fixed_assets]: {
      fields: contract_fixed_assets,
      tab_name: "contract_fixed_assets",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_linked_parking]: {
      fields: contract_linked_parking,
      tab_name: "contract_linked_parking",
      formType: "grid",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [APARTMENT_STEPS_CONTRACT.apartment_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

const shop_sale_contract_group = {
  forms: {
    [SHOP_STEPS_CONTRACT.shop_contract_general]: { fields: shop_sale_contract },
    [SHOP_STEPS_CONTRACT.shop_contract_financial]: {
      fields: contract_sale_financial,
      tab_name: "contract_sale_financial",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_commission]: {
      fields: contract_commission,
    },
    [SHOP_STEPS_CONTRACT.shop_contract_terms]: { fields: contract_terms },
    [SHOP_STEPS_CONTRACT.shop_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_fixed_assets]: {
      fields: contract_fixed_assets,
      tab_name: "contract_fixed_assets",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_linked_parking]: {
      fields: contract_linked_parking,
      tab_name: "contract_linked_parking",
      formType: "grid",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [SHOP_STEPS_CONTRACT.shop_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

const parking_sale_contract_group = {
  forms: {
    [PARKING_STEPS_CONTRACT.parking_contract_general]: {
      fields: parking_sale_contract,
      tab_name: "parking_sale_contract",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_financial]: {
      fields: contract_sale_financial_parking,
      tab_name: "contract_sale_financial_parking",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_commission]: {
      fields: contract_commission,
      tab_name: "contract_commission",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_terms]: { fields: contract_terms },
    [PARKING_STEPS_CONTRACT.parking_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [PARKING_STEPS_CONTRACT.parking_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

const land_sale_contract_group = {
  forms: {
    [LAND_STEPS_CONTRACT.land_contract_general]: { fields: land_sale_contract },
    [LAND_STEPS_CONTRACT.land_contract_financial]: {
      fields: contract_sale_financial,
      tab_name: "contract_sale_financial",
    },
    // payments
    [LAND_STEPS_CONTRACT.land_contract_commission]: {
      fields: contract_commission,
    },
    [LAND_STEPS_CONTRACT.land_contract_terms]: { fields: contract_terms },
    [LAND_STEPS_CONTRACT.land_contract_pictures]: {
      fields: contract_pictures,
      tab_name: "contract_pictures",
      formType: "gallery",
    },
    [LAND_STEPS_CONTRACT.land_contract_other_fees]: {
      fields: contract_other_fees,
      tab_name: "contract_other_fees",
      formType: "grid",
    },
    [LAND_STEPS_CONTRACT.land_contract_fixed_assets]: {
      fields: contract_fixed_assets,
      tab_name: "contract_fixed_assets",
      formType: "grid",
    },
    [LAND_STEPS_CONTRACT.land_contract_linked_parking]: {
      fields: contract_linked_parking,
      tab_name: "contract_linked_parking",
      formType: "grid",
    },
    [LAND_STEPS_CONTRACT.land_contract_termination]: {
      fields: contract_termination,
      tab_name: "contract_termination",
    },
    [LAND_STEPS_CONTRACT.land_contract_recipes_numbers]: {
      fields: contract_receipt_number,
      tab_name: "contract_receipt_number",
      formType: "grid",
    },
  },
};

export const CONTRACTS_FORM = {
  apartment_rent_contract: apartment_rent_contract_group,
  shop_rent_contract: shop_rent_contract_group,
  parking_rent_contract: parking_rent_contract_group,
  apartment_sale_contract: apartment_sale_contract_group,
  shop_sale_contract: shop_sale_contract_group,
  parking_sale_contract: parking_sale_contract_group,
  land_sale_contract: land_sale_contract_group,

  //
  termination_fines_grid,
};

// unused
const contract_fee = [
  { name: "id", type: "uuid", required: false, hide_in_form: true },
  { name: "number", type: "number", required: false, hide_in_form: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
    hide_in_form: true,
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
  { name: "entrynumber", type: "number", required: false },
  { name: "create_entry", type: "boolean", required: false, key: "switch" },
];
const contract_payments = [];
