const contract_cycle = [
  { label: "id", name: "id", type: "uuid", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "contract_documented",
    name: "contract_documented",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_certifying",
    name: "contract_certifying",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_certifying_body",
    name: "contract_certifying_body",
    type: "text",
    required: false,
  },
  {
    label: "contract_received",
    name: "contract_received",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_delivered",
    name: "contract_delivered",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_signed",
    name: "contract_signed",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "municipal_license_num",
    name: "municipal_license_num",
    type: "number",
    required: false,
  },
  {
    label: "municipal_license_from",
    name: "municipal_license_from",
    type: "date",
    required: false,
  },
  {
    label: "municipal_license_to",
    name: "municipal_license_to",
    type: "date",
    required: false,
  },
  {
    label: "license_num",
    name: "license_num",
    type: "number",
    required: false,
  },
  {
    label: "license_from",
    name: "license_from",
    type: "date",
    required: false,
  },
  { label: "license_to", name: "license_to", type: "date", required: false },
  {
    label: "civil_license_num",
    name: "civil_license_num",
    type: "number",
    required: false,
  },
  {
    label: "civil_license_from",
    name: "civil_license_from",
    type: "date",
    required: false,
  },
  {
    label: "civil_license_to",
    name: "civil_license_to",
    type: "date",
    required: false,
  },
];

const contract_linked_parking = [
  { label: "id", name: "id", type: "uuid", required: false },
  { label: "created_at", name: "created_at", type: "date", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "building_id",
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    label: "account_id",
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "main_contract_id",
    name: "main_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
];

const contract_pictures = [
  { label: "id", name: "id", type: "uuid", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "picture",
    name: "picture",
    type: "file",
    required: false,
    key: "image",
  },
];


//  need to generate

const contract_termination = [
  {
    label: "termination_date",
    name: "termination_date",
    type: "date",
    required: false,
  },
  {
    label: "owner_total_amount",
    name: "owner_total_amount",
    type: "number",
    required: false,
  },
  { label: "new_amount", name: "new_amount", type: "number", required: false },
  { label: "round_to", name: "round_to", type: "text", required: false },
  {
    label: "revenue_note",
    name: "revenue_note",
    type: "text",
    required: false,
  },
  { label: "fines", name: "fines", type: "text", required: false },
  {
    label: "fines_revenue_account_id",
    name: "fines_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { label: "fine_note", name: "fine_note", type: "text", required: false },
  {
    label: "evacuation_request",
    name: "evacuation_request",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "evacuation_date",
    name: "evacuation_date",
    type: "date",
    required: false,
  },
  {
    label: "clearance_printed",
    name: "clearance_printed",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "clearance_printed_date",
    name: "clearance_printed_date",
    type: "date",
    required: false,
  },
];


const contract_log_file = [
  {
    name: "id",
    type: "integer",
    default_value: "nextval('logfile_id_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "username",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "computername",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardid",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "odate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "opration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial767",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];

 const contract_flat_assets = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('contractflatassets_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "assetsguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "value",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial804",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];

const contract_fine = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "number", required: false },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
];

const apartment_contract_fee = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "number", required: false },
  { name: "entrynumber", type: "number", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "create_entry", type: "boolean", key: "switch", required: false },
  { name: "note", type: "text", required: false },
];
