// contracts
const apartment_contract_fee = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "int4", required: false },
  { name: "entrynumber", type: "int4", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "date", type: "timestamp", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "float8", required: false },
  { name: "create_entry", type: "bool", required: false },
  { name: "note", type: "text", required: false },
];
const apartment_contract_fine = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "int4", required: false },
  { name: "value", type: "float8", required: false },
  { name: "note", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
];
const apartment_contract_reciept = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "int4", required: false },
  { name: "seclvl", type: "int4", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "no", type: "text", required: false },
  { name: "date", type: "timestamptz", required: false },
  { name: "note", type: "text", required: false },
];

// const _group = {
//   steps: [
//   ],
//   forms: {
//   },
// };
const flat_contract_receipt_number = [
  { name: "id", type: "uuid", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "receipt_number", type: "int4", required: false },
  { name: "receipt_date", type: "date", required: false },
  { name: "receipt_statement", type: "text", required: false },
];

const land = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  { name: "number", type: "text", required: false },
  { name: "type", type: "int2", required: false },
  { name: "no", type: "varchar", required: false },
  { name: "ban", type: "bool", required: false },
  { name: "land_no", type: "text", required: false },
  { name: "name", type: "varchar", required: false },
  { name: "last_name", type: "varchar", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "customer",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  { name: "city", type: "varchar", required: false },
  { name: "region", type: "varchar", required: false },
  { name: "space", type: "varchar", required: false },
  { name: "area", type: "float4", required: false },
  { name: "area_unit", type: "varchar", required: false },
  { name: "price", type: "float4", required: false },
  { name: "license_no", type: "varchar", required: false },
  { name: "license", type: "varchar", required: false },
  { name: "license_date", type: "date", required: false },
  { name: "details", type: "text", required: false },
  { name: "land_type", type: "int4", required: false },
  { name: "side", type: "varchar", required: false },
  { name: "street_name", type: "varchar", required: false },
  { name: "street_count", type: "int4", required: false },
  { name: "buildble", type: "bool", required: false },
  { name: "landowner", type: "int4", required: false },
  { name: "begin_land_value", type: "float4", required: false },
  {
    name: "currency_begin_land_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency_begin_land",
    ref_col: "id",
  },
  { name: "currency_val_begin_land", type: "float4", required: false },
  {
    name: "begin_land_cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "begin_land_cost_center",
    ref_col: "id",
  },
  {
    name: "currency_purchase_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency_purchase",
    ref_col: "id",
  },
  { name: "currency_val_purchase", type: "float4", required: false },
  { name: "purchase_note", type: "text", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "cuowner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cuowner",
    ref_col: "id",
  },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "bank_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "bank_account",
    ref_col: "id",
  },
  { name: "commission_percent", type: "float4", required: false },
  {
    name: "account_comm_income_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account_comm_income",
    ref_col: "id",
  },
  { name: "used_end_date", type: "date", required: false },
  {
    name: "customer_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "customer_owner",
    ref_col: "id",
  },
  {
    name: "owner_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "owner_account",
    ref_col: "id",
  },
  { name: "identity_value", type: "float4", required: false },
  {
    name: "currency_identity_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currencyentity_id",
    ref_col: "id",
  },
  { name: "currency_valid_entity", type: "float4", required: false },
  { name: "identity_begin_date", type: "date", required: false },
  { name: "identity_end_date", type: "date", required: false },
  { name: "create_entry_investment", type: "bool", required: false },
  {
    name: "identity_entry_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "identity_entry",
    ref_col: "id",
  },
  { name: "identity_note", type: "text", required: false },
  { name: "ltn_land_type", type: "text", required: false },
  { name: "ltn_city", type: "varchar", required: false },
  { name: "ltn_region", type: "varchar", required: false },
  { name: "ltn_space", type: "varchar", required: false },
  { name: "ltn_license", type: "varchar", required: false },
  { name: "ltn_side", type: "varchar", required: false },
  { name: "rent", type: "float4", required: false },
  {
    name: "rent_currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "rent_currency",
    ref_col: "id",
  },
];

const land_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "bool", required: false },
  { name: "edit_date", type: "timestamptz", required: false },
  { name: "deliver_date", type: "timestamptz", required: false },
  { name: "is_auto_renewal", type: "bool", required: false },
  { name: "contract_no", type: "varchar", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "customer",
    ref_col: "id",
  },
  { name: "description", type: "varchar", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "villa_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "villa",
    ref_col: "id",
  },
  {
    name: "land_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "land",
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  { name: "from_date", type: "timestamptz", required: false },
  { name: "to_date", type: "timestamptz", required: false },
  { name: "period", type: "int4", required: false },
  { name: "rent", type: "float8", required: false },
  { name: "rent_contract_type", type: "int4", required: false },
  { name: "monthly_value", type: "float8", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "float8", required: false },
  { name: "discount_percent", type: "float8", required: false },
  { name: "discount_value", type: "float8", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "discount_account",
    ref_col: "id",
  },
  { name: "pay_type", type: "int4", required: false },
  { name: "note", type: "varchar", required: false },
  { name: "note2", type: "varchar", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "revenue_account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cust_account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "float8", required: false },
  { name: "commission_from_cust_value", type: "float8", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_cust",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "float8", required: false },
  { name: "commission_from_owner_value", type: "float8", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_owner",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_income_next_year",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "varchar", required: false },
  { name: "ac_commission_from_cust_note", type: "varchar", required: false },
  { name: "commission_from_seller_percent", type: "float8", required: false },
  { name: "commission_from_seller_value", type: "float8", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_seller_commission",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_expense",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "varchar", required: false },
  { name: "other_fee1", type: "float8", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account1",
    ref_col: "id",
  },
  { name: "other_fee2", type: "float8", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_feeaccount2",
    ref_col: "id",
  },
  { name: "other_fee3", type: "float8", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account3",
    ref_col: "id",
  },
  { name: "other_fee4", type: "float8", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account4",
    ref_col: "id",
  },
  { name: "other_fee5", type: "float8", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account5",
    ref_col: "id",
  },
  { name: "contract_finish", type: "bool", required: false },
  { name: "contract_finish_date", type: "timestamptz", required: false },
  { name: "edit_contract_finish_date", type: "timestamptz", required: false },
  { name: "resulting_amount", type: "float8", required: false },
  { name: "resulting_amount2", type: "float8", required: false },
  { name: "resulting_note", type: "varchar", required: false },
  { name: "fine", type: "float8", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "varchar", required: false },
  { name: "create_resulting_entry", type: "bool", required: false },
  { name: "insurance_value", type: "float8", required: false },
  { name: "insurance_value_old", type: "float8", required: false },
  { name: "contract_price", type: "float8", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "float8", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "varchar", required: false },
  { name: "rent_type", type: "varchar", required: false },
  { name: "terms_of_payment", type: "varchar", required: false },
  { name: "step1_complete", type: "bool", required: false },
  { name: "step2_complete", type: "bool", required: false },
  { name: "step3_complete", type: "bool", required: false },
  { name: "step4_complete", type: "bool", required: false },
  { name: "step5_complete", type: "bool", required: false },
  { name: "certification", type: "varchar", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch",
    ref_col: "id",
  },
  { name: "create_contract_entry", type: "bool", required: false },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "fine_revenue_account",
    ref_col: "id",
  },
  { name: "new_state", type: "int4", required: false },
  { name: "license1_no", type: "varchar", required: false },
  { name: "license2_no", type: "varchar", required: false },
  { name: "license3_no", type: "varchar", required: false },
  { name: "license1_date1", type: "timestamptz", required: false },
  { name: "license2_date1", type: "timestamptz", required: false },
  { name: "license3_date1", type: "timestamptz", required: false },
  { name: "license1_date2", type: "timestamptz", required: false },
  { name: "license2_date2", type: "timestamptz", required: false },
  { name: "license3_date2", type: "timestamptz", required: false },
  { name: "ltnrent_duration", type: "varchar", required: false },
  { name: "ltnrentype", type: "varchar", required: false },
  { name: "ltntermsofpayment", type: "varchar", required: false },
  { name: "is_rounded", type: "bool", required: false },
  { name: "judicial", type: "bool", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "prv_contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "float8", required: false },
  { name: "add_value", type: "float8", required: false },
];

const land_contract_fee = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  { name: "number", type: "text", required: false },
  { name: "entry_number", type: "int4", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "float8", required: false },
  { name: "gen_entries", type: "bool", required: false },
  { name: "note", type: "text", required: false },
];
const land_contract_receipt_number = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "number", type: "text", required: false },
  { name: "type", type: "int4", required: false },
  { name: "no", type: "varchar", required: false },
  { name: "date", type: "date", required: false },
  { name: "note", type: "text", required: false },
];

const land_wallet = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  { name: "number", type: "text", required: false },
  {
    name: "land_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "land",
    ref_col: "id",
  },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "main_cost", type: "float8", required: false },
  { name: "expense", type: "float8", required: false },
  { name: "begin_date", type: "date", required: false },
  { name: "sale_date", type: "date", required: false },
  { name: "sale_value", type: "float8", required: false },
];

const office_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "bool", required: false },
  { name: "edit_date", type: "timestamptz", required: false },
  { name: "deliver_date", type: "timestamptz", required: false },
  { name: "is_auto_renewal", type: "bool", required: false },
  { name: "contract_no", type: "varchar", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "customer",
    ref_col: "id",
  },
  { name: "description", type: "varchar", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "office_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "office",
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  { name: "from_date", type: "timestamptz", required: false },
  { name: "to_date", type: "timestamptz", required: false },
  { name: "period", type: "int4", required: false },
  { name: "rent", type: "float8", required: false },
  { name: "rent_contract_type", type: "int4", required: false },
  { name: "monthly_value", type: "float8", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "float8", required: false },
  { name: "discount_percent", type: "float8", required: false },
  { name: "discount_value", type: "float8", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "discount_account",
    ref_col: "id",
  },
  { name: "pay_type", type: "int4", required: false },
  { name: "note", type: "varchar", required: false },
  { name: "note2", type: "varchar", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "revenue_account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cust_account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "float8", required: false },
  { name: "commission_from_cust_value", type: "float8", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_cust",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "float8", required: false },
  { name: "commission_from_owner_value", type: "float8", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_owner",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_income_next_year",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "varchar", required: false },
  { name: "ac_commission_from_cust_note", type: "varchar", required: false },
  { name: "commission_from_seller_percent", type: "float8", required: false },
  { name: "commission_from_seller_value", type: "float8", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_seller_commission",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_expense",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "varchar", required: false },
  { name: "other_fee1", type: "float8", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account1",
    ref_col: "id",
  },
  { name: "other_fee2", type: "float8", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_feeaccount2",
    ref_col: "id",
  },
  { name: "other_fee3", type: "float8", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account3",
    ref_col: "id",
  },
  { name: "other_fee4", type: "float8", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account4",
    ref_col: "id",
  },
  { name: "other_fee5", type: "float8", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account5",
    ref_col: "id",
  },
  { name: "contract_finish", type: "bool", required: false },
  { name: "contract_finish_date", type: "timestamptz", required: false },
  { name: "edit_contract_finish_date", type: "timestamptz", required: false },
  { name: "resulting_amount", type: "float8", required: false },
  { name: "resulting_amount2", type: "float8", required: false },
  { name: "resulting_note", type: "varchar", required: false },
  { name: "fine", type: "float8", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "varchar", required: false },
  { name: "create_resulting_entry", type: "bool", required: false },
  { name: "insurance_value", type: "float8", required: false },
  { name: "insurance_value_old", type: "float8", required: false },
  { name: "contract_price", type: "float8", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "float8", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "varchar", required: false },
  { name: "rent_type", type: "varchar", required: false },
  { name: "terms_of_payment", type: "varchar", required: false },
  { name: "step1_complete", type: "bool", required: false },
  { name: "step2_complete", type: "bool", required: false },
  { name: "step3_complete", type: "bool", required: false },
  { name: "step4_complete", type: "bool", required: false },
  { name: "step5_complete", type: "bool", required: false },
  { name: "certification", type: "varchar", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch",
    ref_col: "id",
  },
  { name: "create_contract_entry", type: "bool", required: false },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "fine_revenue_account",
    ref_col: "id",
  },
  { name: "new_state", type: "int4", required: false },
  { name: "license1_no", type: "varchar", required: false },
  { name: "license2_no", type: "varchar", required: false },
  { name: "license3_no", type: "varchar", required: false },
  { name: "license1_date1", type: "timestamptz", required: false },
  { name: "license2_date1", type: "timestamptz", required: false },
  { name: "license3_date1", type: "timestamptz", required: false },
  { name: "license1_date2", type: "timestamptz", required: false },
  { name: "license2_date2", type: "timestamptz", required: false },
  { name: "license3_date2", type: "timestamptz", required: false },
  { name: "ltnrent_duration", type: "varchar", required: false },
  { name: "ltnrentype", type: "varchar", required: false },
  { name: "ltntermsofpayment", type: "varchar", required: false },
  { name: "is_rounded", type: "bool", required: false },
  { name: "judicial", type: "bool", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "prv_contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "float8", required: false },
  { name: "add_value", type: "float8", required: false },
];

const parking_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "bool", required: false },
  { name: "edit_date", type: "timestamptz", required: false },
  { name: "deliver_date", type: "timestamptz", required: false },
  { name: "contract_kind", type: "int4", required: false },
  { name: "is_auto_renewal", type: "bool", required: false },
  { name: "contract_no", type: "varchar", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "customer",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "parking",
    ref_col: "id",
  },
  { name: "description", type: "varchar", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  {
    name: "apartment_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment_contract",
    ref_col: "id",
  },
  { name: "from_date", type: "timestamptz", required: false },
  { name: "to_date", type: "timestamptz", required: false },
  { name: "period", type: "int4", required: false },
  { name: "rent", type: "float8", required: false },
  { name: "rent_contract_type", type: "int4", required: false },
  { name: "monthly_value", type: "float8", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "float8", required: false },
  { name: "discount_percent", type: "float8", required: false },
  { name: "discount_value", type: "float8", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "discount_account",
    ref_col: "id",
  },
  { name: "pay_type", type: "int4", required: false },
  { name: "note", type: "varchar", required: false },
  { name: "note2", type: "varchar", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "revenue_account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cust_account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "float8", required: false },
  { name: "commission_from_cust_value", type: "float8", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_cust",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "float8", required: false },
  { name: "commission_from_owner_value", type: "float8", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_from_owner",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_income_next_year",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "varchar", required: false },
  { name: "ac_commission_from_cust_note", type: "varchar", required: false },
  { name: "commission_from_seller_percent", type: "float8", required: false },
  { name: "commission_from_seller_value", type: "float8", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_seller_commission",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "ac_commission_expense",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "varchar", required: false },
  { name: "other_fee1", type: "float8", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account1",
    ref_col: "id",
  },
  { name: "other_fee2", type: "float8", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_feeaccount2",
    ref_col: "id",
  },
  { name: "other_fee3", type: "float8", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account3",
    ref_col: "id",
  },
  { name: "other_fee4", type: "float8", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account4",
    ref_col: "id",
  },
  { name: "other_fee5", type: "float8", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "other_fee_account5",
    ref_col: "id",
  },
  { name: "contract_finish", type: "bool", required: false },
  { name: "contract_finish_date", type: "timestamptz", required: false },
  { name: "edit_contract_finish_date", type: "timestamptz", required: false },
  { name: "resulting_amount", type: "float8", required: false },
  { name: "resulting_amount2", type: "float8", required: false },
  { name: "resulting_note", type: "varchar", required: false },
  { name: "fine", type: "float8", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "varchar", required: false },
  { name: "create_resulting_entry", type: "bool", required: false },
  { name: "insurance_value", type: "float8", required: false },
  { name: "insurance_value_old", type: "float8", required: false },
  { name: "contract_price", type: "float8", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "float8", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "varchar", required: false },
  { name: "rent_type", type: "varchar", required: false },
  { name: "terms_of_payment", type: "varchar", required: false },
  { name: "step1_complete", type: "bool", required: false },
  { name: "step2_complete", type: "bool", required: false },
  { name: "step3_complete", type: "bool", required: false },
  { name: "step4_complete", type: "bool", required: false },
  { name: "step5_complete", type: "bool", required: false },
  { name: "certification", type: "varchar", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch",
    ref_col: "id",
  },
  { name: "card_no", type: "varchar", required: false },
  { name: "car_no", type: "varchar", required: false },
  { name: "car_type", type: "varchar", required: false },
  { name: "car_color", type: "varchar", required: false },
  { name: "emirate", type: "varchar", required: false },
  { name: "create_contract_entry", type: "bool", required: false },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "fine_revenue_account",
    ref_col: "id",
  },
  { name: "new_state", type: "int4", required: false },
  { name: "license1_no", type: "varchar", required: false },
  { name: "license2_no", type: "varchar", required: false },
  { name: "license3_no", type: "varchar", required: false },
  { name: "license1_date1", type: "timestamptz", required: false },
  { name: "license2_date1", type: "timestamptz", required: false },
  { name: "license3_date1", type: "timestamptz", required: false },
  { name: "license1_date2", type: "timestamptz", required: false },
  { name: "license2_date2", type: "timestamptz", required: false },
  { name: "license3_date2", type: "timestamptz", required: false },
  { name: "ltnrent_duration", type: "varchar", required: false },
  { name: "ltnrentype", type: "varchar", required: false },
  { name: "ltntermsofpayment", type: "varchar", required: false },
  { name: "is_rounded", type: "bool", required: false },
  { name: "judicial", type: "bool", required: false },
  { name: "is_return_insurance", type: "bool", required: false },
  { name: "return_insurance_date", type: "timestamptz", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "prv_contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "float8", required: false },
  { name: "add_value", type: "float8", required: false },
];

const parking_contract_fee = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  { name: "number", type: "text", required: false },
  { name: "entry_number", type: "int4", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "float4", required: false },
  { name: "gen_entries", type: "bool", required: false },
  { name: "note", type: "text", required: false },
];
const parking_contract_receipt_number = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "number", type: "text", required: false },
  { name: "type", type: "int2", required: false },
  { name: "no", type: "text", required: false },
  { name: "date", type: "date", required: false },
  { name: "note", type: "text", required: false },
];

const parking_wallet = [
  { name: "id", type: "uuid", required: false },
  { name: "created_at", type: "timestamptz", required: false },
  { name: "number", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "parking",
    ref_col: "id",
  },
  { name: "main_cost", type: "float8", required: false },
  { name: "expense", type: "float4", required: false },
  { name: "begin_date", type: "date", required: false },
  { name: "sale_date", type: "date", required: false },
  { name: "sale_value", type: "float8", required: false },
];

