const contract_cycle = [
  { label: "id", name: "id", type: "uuid", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "contract_documented",
    name: "contract_documented",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_certifying",
    name: "contract_certifying",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_certifying_body",
    name: "contract_certifying_body",
    type: "text",
    required: false,
  },
  {
    label: "contract_received",
    name: "contract_received",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_delivered",
    name: "contract_delivered",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "contract_signed",
    name: "contract_signed",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "municipal_license_num",
    name: "municipal_license_num",
    type: "number",
    required: false,
  },
  {
    label: "municipal_license_from",
    name: "municipal_license_from",
    type: "date",
    required: false,
  },
  {
    label: "municipal_license_to",
    name: "municipal_license_to",
    type: "date",
    required: false,
  },
  {
    label: "license_num",
    name: "license_num",
    type: "number",
    required: false,
  },
  {
    label: "license_from",
    name: "license_from",
    type: "date",
    required: false,
  },
  { label: "license_to", name: "license_to", type: "date", required: false },
  {
    label: "civil_license_num",
    name: "civil_license_num",
    type: "number",
    required: false,
  },
  {
    label: "civil_license_from",
    name: "civil_license_from",
    type: "date",
    required: false,
  },
  {
    label: "civil_license_to",
    name: "civil_license_to",
    type: "date",
    required: false,
  },
];

const contract_linked_parking = [
  { label: "id", name: "id", type: "uuid", required: false },
  { label: "created_at", name: "created_at", type: "date", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "building_id",
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    label: "account_id",
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "main_contract_id",
    name: "main_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
];

const contract_pictures = [
  { label: "id", name: "id", type: "uuid", required: false },
  {
    label: "contract_id",
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    label: "picture",
    name: "picture",
    type: "file",
    required: false,
    key: "image",
  },
];


//  need to generate

const contract_termination = [
  {
    label: "termination_date",
    name: "termination_date",
    type: "date",
    required: false,
  },
  {
    label: "owner_total_amount",
    name: "owner_total_amount",
    type: "number",
    required: false,
  },
  { label: "new_amount", name: "new_amount", type: "number", required: false },
  { label: "round_to", name: "round_to", type: "text", required: false },
  {
    label: "revenue_note",
    name: "revenue_note",
    type: "text",
    required: false,
  },
  { label: "fines", name: "fines", type: "text", required: false },
  {
    label: "fines_revenue_account_id",
    name: "fines_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { label: "fine_note", name: "fine_note", type: "text", required: false },
  {
    label: "evacuation_request",
    name: "evacuation_request",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "evacuation_date",
    name: "evacuation_date",
    type: "date",
    required: false,
  },
  {
    label: "clearance_printed",
    name: "clearance_printed",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "clearance_printed_date",
    name: "clearance_printed_date",
    type: "date",
    required: false,
  },
];


const contract_log_file = [
  {
    name: "id",
    type: "integer",
    default_value: "nextval('logfile_id_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "username",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "computername",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardid",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "odate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "opration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial767",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];

 const contract_flat_assets = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('contractflatassets_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "assetsguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "value",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial804",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];

const contract_fine = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "number", required: false },
  { name: "value", type: "number", required: false },
  { name: "note", type: "text", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
];

const apartment_contract_fee = [
  { name: "id", type: "uuid", required: false },
  { name: "number", type: "number", required: false },
  { name: "entrynumber", type: "number", required: false },
  {
    name: "contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "date", type: "date", required: false },
  {
    name: "account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "value", type: "number", required: false },
  { name: "create_entry", type: "boolean", key: "switch", required: false },
  { name: "note", type: "text", required: false },
];

// contracts

// general contract
const contract = [
  { label: "id", name: "id", type: "uuid", required: false },
  { label: "number", name: "number", type: "number", required: false },
  {
    label: "feedback",
    name: "feedback",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "lawsuit",
    name: "lawsuit",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "client_id",
    name: "client_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "building_id",
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    label: "apartment_id",
    name: "apartment_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "apartment",
    ref_col: "id",
  },
  { label: "description", name: "description", type: "text", required: false },
  {
    label: "lessor_id",
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    label: "seller_id",
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  { label: "trade_name", name: "trade_name", type: "text", required: false },
  {
    label: "nationality",
    name: "nationality",
    type: "number",
    required: false,
  },
  { label: "work_phone", name: "work_phone", type: "number", required: false },
  { label: "phono", name: "phono", type: "number", required: false },
  { label: "area", name: "area", type: "number", required: false },
  { label: "status", name: "status", type: "text", required: false },
  { label: "date", name: "date", type: "date", required: false },
  {
    label: "contract_place",
    name: "contract_place",
    type: "text",
    required: false,
  },
  {
    label: "rental_period_text",
    name: "rental_period_text",
    type: "text",
    required: false,
  },
  { label: "rent_type", name: "rent_type", type: "text", required: false },
  {
    label: "contract_status",
    name: "contract_status",
    type: "text",
    required: false,
  },
  {
    label: "aprtment_status",
    name: "aprtment_status",
    type: "text",
    required: false,
  },
  { label: "ownership", name: "ownership", type: "text", required: false },
  {
    label: "renting_purpose",
    name: "renting_purpose",
    type: "text",
    required: false,
  },
  {
    label: "resident_count",
    name: "resident_count",
    type: "number",
    required: false,
  },
  {
    label: "payment_method",
    name: "payment_method",
    type: "text",
    required: false,
  },
  {
    label: "previous_contract_count",
    name: "previous_contract_count",
    type: "number",
    required: false,
  },
  {
    label: "current_contract_count",
    name: "current_contract_count",
    type: "number",
    required: false,
  },
  {
    label: "current_contract_count",
    name: "current_contract_count",
    type: "number",
    required: false,
  },
  {
    label: "contract_type",
    name: "contract_type",
    type: "number",
    required: false,
  },
  {
    label: "contract_value",
    name: "contract_value",
    type: "number",
    required: false,
  },
  {
    label: "monthly_value",
    name: "monthly_value",
    type: "number",
    required: false,
  },
  {
    label: "currency_id",
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  {
    label: "currency_val",
    name: "currency_val",
    type: "number",
    required: false,
  },
  {
    label: "discount_rate",
    name: "discount_rate",
    type: "number",
    required: false,
  },
  {
    label: "discount_value",
    name: "discount_value",
    type: "number",
    required: false,
  },
  {
    label: "final_price",
    name: "final_price",
    type: "number",
    required: false,
  },
  {
    label: "discount_account_id",
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "previous_insurance",
    name: "previous_insurance",
    type: "number",
    required: false,
  },
  {
    label: "current_insurance_percentage",
    name: "current_insurance_percentage",
    type: "number",
    required: false,
  },
  {
    label: "current_insurance_value",
    name: "current_insurance_value",
    type: "number",
    required: false,
  },
  {
    label: "contract_price",
    name: "contract_price",
    type: "number",
    required: false,
  },
  {
    label: "contract_validate",
    name: "contract_validate",
    type: "number",
    required: false,
  },
  {
    label: "electricity_insurance",
    name: "electricity_insurance",
    type: "number",
    required: false,
  },
  {
    label: "last_meter_reading",
    name: "last_meter_reading",
    type: "number",
    required: false,
  },
  {
    label: "contract_duration",
    name: "contract_duration",
    type: "number",
    required: false,
  },
  { label: "start_date", name: "start_date", type: "date", required: false },
  { label: "end_date", name: "end_date", type: "date", required: false },
  {
    label: "payment_type",
    name: "payment_type",
    type: "number",
    required: false,
  },
  {
    label: "cost_center_id",
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    label: "revenue_account_id",
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "customer_account_id",
    name: "customer_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "insurance_account_id",
    name: "insurance_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "contract_price_account_id",
    name: "contract_price_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "contract_validate_account_id",
    name: "contract_validate_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { label: "other_fees", name: "other_fees", type: "text", required: false },
  {
    label: "fee_revenue_account_id",
    name: "fee_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "custom_duration_value",
    name: "custom_duration_value",
    type: "number",
    required: false,
  },
  {
    label: "commission_percentage",
    name: "commission_percentage",
    type: "number",
    required: false,
  },
  {
    label: "commission_value",
    name: "commission_value",
    type: "number",
    required: false,
  },
  {
    label: "commission_account_id",
    name: "commission_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "commission_note",
    name: "commission_note",
    type: "text",
    required: false,
  },
  {
    label: "commission_from_owner_percentage",
    name: "commission_from_owner_percentage",
    type: "number",
    required: false,
  },
  {
    label: "commission_from_owner_value",
    name: "commission_from_owner_value",
    type: "number",
    required: false,
  },
  {
    label: "commission_from_owner_account_id",
    name: "commission_from_owner_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    label: "commission_from_owner_note",
    name: "commission_from_owner_note",
    type: "text",
    required: false,
  },

  {
    label: "termination_date",
    name: "termination_date",
    type: "date",
    required: false,
  },
  {
    label: "owner_total_amount",
    name: "owner_total_amount",
    type: "number",
    required: false,
  },
  { label: "new_amount", name: "new_amount", type: "number", required: false },
  { label: "round_to", name: "round_to", type: "text", required: false },
  {
    label: "revenue_note",
    name: "revenue_note",
    type: "text",
    required: false,
  },
  { label: "fines", name: "fines", type: "text", required: false },
  {
    label: "fines_revenue_account_id",
    name: "fines_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { label: "fine_note", name: "fine_note", type: "text", required: false },
  {
    label: "evacuation_request",
    name: "evacuation_request",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "evacuation_date",
    name: "evacuation_date",
    type: "date",
    required: false,
  },
  {
    label: "clearance_printed",
    name: "clearance_printed",
    type: "checkbox",
    key: "switch",
    required: false,
  },
  {
    label: "clearance_printed_date",
    name: "clearance_printed_date",
    type: "date",
    required: false,
  },
];
const land_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "boolean", key: "switch", required: false },
  { name: "edit_date", type: "date", required: false },
  { name: "deliver_date", type: "date", required: false },
  { name: "is_auto_renewal", type: "boolean", key: "switch", required: false },
  { name: "contract_no", type: "text", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "villa_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "villa",
    ref_col: "id",
  },
  {
    name: "land_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "land",
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  { name: "from_date", type: "date", required: false },
  { name: "to_date", type: "date", required: false },
  { name: "period", type: "number", required: false },
  { name: "rent", type: "number", required: false },
  { name: "rent_contract_type", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_percent", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "pay_type", type: "number", required: false },
  { name: "note", type: "text", required: false },
  { name: "note2", type: "text", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "number", required: false },
  { name: "commission_from_cust_value", type: "number", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "number", required: false },
  { name: "commission_from_owner_value", type: "number", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "text", required: false },
  { name: "ac_commission_from_cust_note", type: "text", required: false },
  { name: "commission_from_seller_percent", type: "number", required: false },
  { name: "commission_from_seller_value", type: "number", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "text", required: false },
  { name: "other_fee1", type: "number", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee2", type: "number", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee3", type: "number", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee4", type: "number", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee5", type: "number", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "contract_finish", type: "boolean", key: "switch", required: false },
  { name: "contract_finish_date", type: "date", required: false },
  { name: "edit_contract_finish_date", type: "date", required: false },
  { name: "resulting_amount", type: "number", required: false },
  { name: "resulting_amount2", type: "number", required: false },
  { name: "resulting_note", type: "text", required: false },
  { name: "fine", type: "number", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "text", required: false },
  {
    name: "create_resulting_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  { name: "insurance_value", type: "number", required: false },
  { name: "insurance_value_old", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "number", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "text", required: false },
  { name: "rent_type", type: "text", required: false },
  { name: "terms_of_payment", type: "text", required: false },
  { name: "step1_complete", type: "boolean", key: "switch", required: false },
  { name: "step2_complete", type: "boolean", key: "switch", required: false },
  { name: "step3_complete", type: "boolean", key: "switch", required: false },
  { name: "step4_complete", type: "boolean", key: "switch", required: false },
  { name: "step5_complete", type: "boolean", key: "switch", required: false },
  { name: "certification", type: "text", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch", // unknown table // unknown table
    ref_col: "id",
  },
  {
    name: "create_contract_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "new_state", type: "number", required: false },
  { name: "license1_no", type: "text", required: false },
  { name: "license2_no", type: "text", required: false },
  { name: "license3_no", type: "text", required: false },
  { name: "license1_date1", type: "date", required: false },
  { name: "license2_date1", type: "date", required: false },
  { name: "license3_date1", type: "date", required: false },
  { name: "license1_date2", type: "date", required: false },
  { name: "license2_date2", type: "date", required: false },
  { name: "license3_date2", type: "date", required: false },
  { name: "ltnrent_duration", type: "text", required: false },
  { name: "ltnrentype", type: "text", required: false },
  { name: "ltntermsofpayment", type: "text", required: false },
  { name: "is_rounded", type: "boolean", key: "switch", required: false },
  { name: "judicial", type: "boolean", key: "switch", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "number", required: false },
  { name: "add_value", type: "number", required: false },
];

const office_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "boolean", key: "switch", required: false },
  { name: "edit_date", type: "date", required: false },
  { name: "deliver_date", type: "date", required: false },
  { name: "is_auto_renewal", type: "boolean", key: "switch", required: false },
  { name: "contract_no", type: "text", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "office_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "office", // unknown table
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  { name: "from_date", type: "date", required: false },
  { name: "to_date", type: "date", required: false },
  { name: "period", type: "number", required: false },
  { name: "rent", type: "number", required: false },
  { name: "rent_contract_type", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_percent", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "pay_type", type: "number", required: false },
  { name: "note", type: "text", required: false },
  { name: "note2", type: "text", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "number", required: false },
  { name: "commission_from_cust_value", type: "number", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "number", required: false },
  { name: "commission_from_owner_value", type: "number", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "text", required: false },
  { name: "ac_commission_from_cust_note", type: "text", required: false },
  { name: "commission_from_seller_percent", type: "number", required: false },
  { name: "commission_from_seller_value", type: "number", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "text", required: false },
  { name: "other_fee1", type: "number", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee2", type: "number", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee3", type: "number", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee4", type: "number", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee5", type: "number", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "contract_finish", type: "boolean", key: "switch", required: false },
  { name: "contract_finish_date", type: "date", required: false },
  { name: "edit_contract_finish_date", type: "date", required: false },
  { name: "resulting_amount", type: "number", required: false },
  { name: "resulting_amount2", type: "number", required: false },
  { name: "resulting_note", type: "text", required: false },
  { name: "fine", type: "number", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "text", required: false },
  {
    name: "create_resulting_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  { name: "insurance_value", type: "number", required: false },
  { name: "insurance_value_old", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "number", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "text", required: false },
  { name: "rent_type", type: "text", required: false },
  { name: "terms_of_payment", type: "text", required: false },
  { name: "step1_complete", type: "boolean", key: "switch", required: false },
  { name: "step2_complete", type: "boolean", key: "switch", required: false },
  { name: "step3_complete", type: "boolean", key: "switch", required: false },
  { name: "step4_complete", type: "boolean", key: "switch", required: false },
  { name: "step5_complete", type: "boolean", key: "switch", required: false },
  { name: "certification", type: "text", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch", // unknown table // unknown table
    ref_col: "id",
  },
  {
    name: "create_contract_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "new_state", type: "number", required: false },
  { name: "license1_no", type: "text", required: false },
  { name: "license2_no", type: "text", required: false },
  { name: "license3_no", type: "text", required: false },
  { name: "license1_date1", type: "date", required: false },
  { name: "license2_date1", type: "date", required: false },
  { name: "license3_date1", type: "date", required: false },
  { name: "license1_date2", type: "date", required: false },
  { name: "license2_date2", type: "date", required: false },
  { name: "license3_date2", type: "date", required: false },
  { name: "ltnrent_duration", type: "text", required: false },
  { name: "ltnrentype", type: "text", required: false },
  { name: "ltntermsofpayment", type: "text", required: false },
  { name: "is_rounded", type: "boolean", key: "switch", required: false },
  { name: "judicial", type: "boolean", key: "switch", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "number", required: false },
  { name: "add_value", type: "number", required: false },
];

const parking_contract = [
  { name: "id", type: "uuid", required: false },
  { name: "seclvl", type: "text", required: false },
  { name: "mark", type: "boolean", key: "switch", required: false },
  { name: "edit_date", type: "date", required: false },
  { name: "deliver_date", type: "date", required: false },
  { name: "contract_kind", type: "number", required: false },
  { name: "is_auto_renewal", type: "boolean", key: "switch", required: false },
  { name: "contract_no", type: "text", required: false },
  {
    name: "customer_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "building_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "building",
    ref_col: "id",
  },
  {
    name: "parking_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "parking",
    ref_col: "id",
  },
  { name: "description", type: "text", required: false },
  {
    name: "cost_center_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "cost_center",
    ref_col: "id",
  },
  {
    name: "lessor_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "lessor",
    ref_col: "id",
  },
  {
    name: "seller_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "seller",
    ref_col: "id",
  },
  {
    name: "apartment_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract", // unknown table
    ref_col: "id",
  },
  { name: "from_date", type: "date", required: false },
  { name: "to_date", type: "date", required: false },
  { name: "period", type: "number", required: false },
  { name: "rent", type: "number", required: false },
  { name: "rent_contract_type", type: "number", required: false },
  { name: "monthly_value", type: "number", required: false },
  {
    name: "currency_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "id",
  },
  { name: "currency_val", type: "number", required: false },
  { name: "discount_percent", type: "number", required: false },
  { name: "discount_value", type: "number", required: false },
  {
    name: "discount_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "pay_type", type: "number", required: false },
  { name: "note", type: "text", required: false },
  { name: "note2", type: "text", required: false },
  {
    name: "revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "cust_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_cust_percent", type: "number", required: false },
  { name: "commission_from_cust_value", type: "number", required: false },
  {
    name: "ac_commission_from_cust_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "commission_from_owner_percent", type: "number", required: false },
  { name: "commission_from_owner_value", type: "number", required: false },
  {
    name: "ac_commission_from_owner_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_income_next_year_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "ac_commission_from_owner_note", type: "text", required: false },
  { name: "ac_commission_from_cust_note", type: "text", required: false },
  { name: "commission_from_seller_percent", type: "number", required: false },
  { name: "commission_from_seller_value", type: "number", required: false },
  {
    name: "ac_seller_commission_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  {
    name: "ac_commission_expense_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "seller_commnote", type: "text", required: false },
  { name: "other_fee1", type: "number", required: false },
  {
    name: "other_fee_account1_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee2", type: "number", required: false },
  {
    name: "other_feeaccount2_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee3", type: "number", required: false },
  {
    name: "other_fee_account3_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee4", type: "number", required: false },
  {
    name: "other_fee_account4_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "other_fee5", type: "number", required: false },
  {
    name: "other_fee_account5_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "contract_finish", type: "boolean", key: "switch", required: false },
  { name: "contract_finish_date", type: "date", required: false },
  { name: "edit_contract_finish_date", type: "date", required: false },
  { name: "resulting_amount", type: "number", required: false },
  { name: "resulting_amount2", type: "number", required: false },
  { name: "resulting_note", type: "text", required: false },
  { name: "fine", type: "number", required: false },
  { name: "fine_account", type: "uuid", required: false },
  { name: "fine_note", type: "text", required: false },
  {
    name: "create_resulting_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  { name: "insurance_value", type: "number", required: false },
  { name: "insurance_value_old", type: "number", required: false },
  { name: "contract_price", type: "number", required: false },
  { name: "account_contract_price", type: "uuid", required: false },
  { name: "certificate_value", type: "number", required: false },
  { name: "account_certificate_value", type: "uuid", required: false },
  { name: "rent_duration", type: "text", required: false },
  { name: "rent_type", type: "text", required: false },
  { name: "terms_of_payment", type: "text", required: false },
  { name: "step1_complete", type: "boolean", key: "switch", required: false },
  { name: "step2_complete", type: "boolean", key: "switch", required: false },
  { name: "step3_complete", type: "boolean", key: "switch", required: false },
  { name: "step4_complete", type: "boolean", key: "switch", required: false },
  { name: "step5_complete", type: "boolean", key: "switch", required: false },
  { name: "certification", type: "text", required: false },
  {
    name: "branch_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "branch", // unknown table
    ref_col: "id",
  },
  { name: "card_no", type: "text", required: false },
  { name: "car_no", type: "text", required: false },
  { name: "car_type", type: "text", required: false },
  { name: "car_color", type: "text", required: false },
  { name: "emirate", type: "text", required: false },
  {
    name: "create_contract_entry",
    type: "boolean",
    key: "switch",
    required: false,
  },
  {
    name: "fine_revenue_account_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "id",
  },
  { name: "new_state", type: "number", required: false },
  { name: "license1_no", type: "text", required: false },
  { name: "license2_no", type: "text", required: false },
  { name: "license3_no", type: "text", required: false },
  { name: "license1_date1", type: "date", required: false },
  { name: "license2_date1", type: "date", required: false },
  { name: "license3_date1", type: "date", required: false },
  { name: "license1_date2", type: "date", required: false },
  { name: "license2_date2", type: "date", required: false },
  { name: "license3_date2", type: "date", required: false },
  { name: "ltnrent_duration", type: "text", required: false },
  { name: "ltnrentype", type: "text", required: false },
  { name: "ltntermsofpayment", type: "text", required: false },
  { name: "is_rounded", type: "boolean", key: "switch", required: false },
  { name: "judicial", type: "boolean", key: "switch", required: false },
  {
    name: "is_return_insurance",
    type: "boolean",
    key: "switch",
    required: false,
  },
  { name: "return_insurance_date", type: "date", required: false },
  {
    name: "prv_contract_id",
    type: "uuid",
    required: false,
    is_ref: true,
    ref_table: "contract",
    ref_col: "id",
  },
  { name: "add_percent", type: "number", required: false },
  { name: "add_value", type: "number", required: false },
];

// 1.Flat | Apartment
// 2.Parking
// 3.Office
// 4.Shop
// 5.Land

// contract_rent_general
// contract_rent_financial
// contract_rent_fee
// contract_rent_commissions
// contract_rent_cycle
// contract_rent_terms
// contract_rent_pictures
// contract_rent_receipts
// contract_rent_linked_parking
// contract_rent_Terminate
// contract_rent_receipts

// contract_sale_general
// contract_sale_financial
// contract_sale_fee
// contract_sale_commissions
// contract_sale_cycle
// contract_sale_terms
// contract_sale_pictures
// contract_sale_receipts
// contract_sale_linked_parking
// contract_sale_Terminate
// contract_sale_receipts
