import { DropDowns } from "Helpers/functions";

export const account = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('account_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "account",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    default_value: null,
    required: false,
    hide_in: "",
    key: "select",
    list: DropDowns("seclvl"),
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "nsons",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "type",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parentguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "finalguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "account",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "maxdebit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mindebit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxcredit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mincredit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "sumdebit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "sumcredit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial883",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
