export const accountconformity = [
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "accountconformity",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "accountguid",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "cost",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    is_ref: true,
    ref_table: "currency",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "debit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "credit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial906",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
