import { DropDowns } from "Helpers/functions";

export const apartment = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('apartment_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "apartment",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "judicial",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ban",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unifiednum",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "manservantroom",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "driverroom",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "floorno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmenttype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "class",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "overlooking",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costcurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatowner",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerstate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offertype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customername",
    type: "character varying",
    default_value: "''::character varying",
    required: false,
    hide_in: "",
  },
  {
    name: "customerphone",
    type: "character varying",
    default_value: "''::character varying",
    required: false,
    hide_in: "",
  },
  {
    name: "restrained",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "payvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bonddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bathroomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "balconycount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "watercounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "electricitycounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "restraineduserguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "purchasedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "beginlandvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencybeginlandguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalbeginland",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "purchaseaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createpurchaseentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatcost",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lastcontractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnflatkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnapartmenttype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnclass",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnoverlooking",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial020",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
