import { DropDowns } from "Helpers/functions";

export const apartmentoffer = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('apartmentoffer_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "apartmentoffer",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "building",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customer",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "floorno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmenttype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "class",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "overlooking",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatowner",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bathroomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "balconycount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "watercounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "electricitycounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delegated",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custphone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custmobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxoffervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial033",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
