import { DropDowns } from "Helpers/functions";

export const assets = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('assets_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "assets",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "assetsgroupguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isactive",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "assetsareaguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currentassetsareaguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "state",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "importer",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "enteraccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entercostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entercreditcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "enterdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "origin",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "company",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "enternote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "asstesaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "expenseaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "depreciationaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "depreciationtotalaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "profitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lossesaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "evaluationaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shipping",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shippingno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shippingdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "arrivedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "arriveplace",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "importpermit",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customsnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customsdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customsexpense",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shippingnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancecontract",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancebegindate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenanceenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "guaranty",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "guarantybegindate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "guarantyenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "depreciationmode",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isdepreciationmonthly",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "depreciationbegindate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "age",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "depreciationavg",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "scrapvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oldyearextra",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oldyeardecrease",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oldyeardepreciation",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oldyearmaintenance",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "issale",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "saledate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salecustomer",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salesaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salevalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencysaleguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencysaleval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salenote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial099",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
