import { DropDowns } from "Helpers/functions";

export const assetschangearea = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('assetschangearea_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "assetschangearea",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "assetsguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currentareaguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "areaguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial125",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
