import { DropDowns } from "Helpers/functions";

export const billorderrecipient = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('billorderrecipient_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "billorderrecipient",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "srl",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parentguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salebilltype",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "driver",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "carno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial285",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
