import { DropDowns } from "Helpers/functions";

export const buildingreceleccounter = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('buildingreceleccounter_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "buildingreceleccounter",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "service",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "eleccounterno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oldcounter",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "olddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "counter",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial497",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
