import { DropDowns } from "Helpers/functions";

export const building = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('building_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "building",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "emirate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "suburb",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "street",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnemirate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnsuburb",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnstreet",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "basinno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pieceno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildautonumber",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "couponnum",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "licensetype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildyear",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "eleccounterno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "floorcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmentcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmentcountoffloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shopcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costunity",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountbankbuildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cashaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insuranceaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankacccode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parentrentaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parentrentinsuranceaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "opowner",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "datepurchase",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "amountpurchase",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencypurchase",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalpurchase",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerpurchase",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "purchasenotes",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckreceiptbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "receiptdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "receiptamount",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyreceipt",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalreceipt",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "receiptnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "owneraccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identityvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyidentityguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalidentity",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identitybegindate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identityenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "usedenddate",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bhousefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bhouseflatcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mbalancefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mbalanceflatcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "officefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "officecount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingfloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingfloorunder",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingcountunder",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatdrivercount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatservantcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "storecount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentrypurchase",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "crearteentryinvestment",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ownername",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcommincomeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingcost",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bonddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentinfoguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckbuildingpaytypelow",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "showincontract",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "showinreport",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial393",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
