import { DropDowns } from "Helpers/functions";

export const buildin_ffer = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('buildin_ffer_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "buildin_ffer",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "emirate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "suburb",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "street",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "basinno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pieceno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "floorcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmentcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "apartmentcountoffloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shopcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costunity",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bhousefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bhouseflatcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mbalancefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mbalanceflatcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "officefloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "officecount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingfloor",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingfloorunder",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingcountunder",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatdrivercount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatservantcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "storecount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bonddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delegated",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxoffervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landarea",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landareaunit",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custphone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custmobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custaddress",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial376",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
