import { DropDowns } from "Helpers/functions";

export const buildingguard = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('buildingguard_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "buildingguard",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "adjective",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "passportno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "passportexpiredate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "nationality",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnationality",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "personalityno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "phone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "email",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial419",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
