import { DropDowns } from "Helpers/functions";

export const checks = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('checks_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "checks",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mark",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "typeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "internalno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "receiptno",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "value",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "duedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endduedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "noneduedate",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "account",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "obverseaccount",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costobverseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "beneficiary",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note4",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "branchguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salesmanguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "folderdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "folderinternalno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "folderexternalno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkcreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isrounded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "deposition",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial677",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
