import { DropDowns } from "Helpers/functions";

export const checkscollection = [
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "value",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commission",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "losscomm",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returncause",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commaccountcreditguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "kind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delay",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delayaccountdebitguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delayaccountcreditguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delaynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delaycostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finished",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finishdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fixreturn",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fixreturnnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isrounded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "operationcreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returncreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commcreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mark",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial703",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
