import { DropDowns } from "Helpers/functions";

export const checktype = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('checktype_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "checktype",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "menu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmenu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createdentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posted",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posdetcreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posdetautocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posdetautopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posteddefaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posteddefcreditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defownerbuildingposted",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defcustposted",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "postmovecostdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "postmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collected",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedcreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedautocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedentrytypeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedautopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedsanctionbankaccountbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedsanctioncustobverse",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collecteddefaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collecteddefaccountobverseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commaccountdebitguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commaccountcreditguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commownerbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defbuildingcomm",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commtype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defbuildingincomcomm",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedmovecostdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collectedmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commmovecost",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollected",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedcreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedautocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedentrytypeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedautopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedsanctionbankaccountbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedcachbankaccountbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollectedsanctioncustobverse",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollecteddefaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollecteddefaccountobverseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialmovecostdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsement",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementcreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementautocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementautopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementdefaccountdebitguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementdefaccountcreateguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementmovecostdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returned",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedcreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedautocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedautopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedsanctionbankbuilding",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedsanctionbankbuildingcasecollonly",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnedsanctioncustaccountdefaccount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returneddefaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returneddefaccountcreditguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "enableatheroperationonreturn",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnmovecostdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnmovecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delaydefaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delaydefaccountobverseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delaysanctioncustaccountdefaccount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "noteform1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnoteform1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "noteform2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnoteform2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "noteposted",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnoteposted",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "notecollected",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnotecollected",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "notecollectedpartial",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnotecollectedpartial",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "noteendorsement",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnoteendorsement",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "notereturn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnotereturn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "notecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnotecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialnotecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialltnnotecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returnnotecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnreturnnotecommission",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "posteddate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "partialcollecteddate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "collecteddate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endorsementdate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returneddate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autosmsafteradd",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smsmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smsmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckscollectionautosend",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckscollectionimmediate",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckscollectionday",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckscollectionmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckscollectionmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckspartialcollectionautosend",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckspartialcollectionmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckspartialcollectionmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckreturnautosend",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckreturnimmediate",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckreturnday",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckreturnmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smscheckreturnmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smschecksdue",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smschecksdueday",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smschecksduemsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smschecksduemsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial742",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
