import { DropDowns } from "Helpers/functions";

export const contractworkflow = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('contractworkflow_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "contractworkflow",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "printed",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "certification",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custstep1",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custstepdate1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custstep2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custstepdate2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep1",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate3",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep4",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate4",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep5",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate5",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep6",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate6",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstep7",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "compstepdate7",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial905",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
