import { DropDowns } from "Helpers/functions";

export const contracttype = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('contracttype_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "contracttype",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "menu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmenu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isautorenewal",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "revenueaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromcustguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcontractpriceguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcertificatvalueguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fineaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "taxaccount",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount1guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount2guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount3guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount4guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount5guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insuranceaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "servescomm",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcondition",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecost",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintlogpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autocreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrydate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithincom",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithinsurance",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithcontractprice",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithcertificat",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithfee",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithclientcomm",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithownercomm",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithinconendcontract",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithfineendcontract",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithincomcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithinsurancecredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithcontractpricecredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithcertificatcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithfeecredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithclientcommcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithownercommcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithinconendcontractcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithfineendcontractcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithdiscount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithdiscountcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defsmsmobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autosmsafteradd",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smsmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "smsmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autosmsafterend",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endsmsmsg",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endsmsmsgen",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endcontract",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "constraintinsurance",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintreceipt",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintacquittance",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "deflawsuitdebitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "deflawsuitcreditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuitcustaccount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuitcostwithdebitaccount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuitcostwithcreditaccount",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuitlinkuser",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawsuitlinkuserexpense",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unearnedrrevenue",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acincomnextyearguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionexpenseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "opnewcontract",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpaynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpaynoteltn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractnoteltn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "feeentrynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "canbegindateafterdate2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "genentryend",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defpictab",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial853",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
