import { DropDowns } from "Helpers/functions";

export const customer = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('customer_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "customer",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardkind2",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "nationality",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnnationality",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "profession",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnprofession",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "passportno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "passportexpiredate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "domicile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "security",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnsecurity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "phonejob",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trademark",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltntrademark",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insuranceaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "memosecurity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmemosecurity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnaddress",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "boxno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "personalityno1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "personalityno2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fax",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "email",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "adjective",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnadjective",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckhideinsearch",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ban",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bancontract",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankacccode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "birthday",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "domicileenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "personalityenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote4",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote5",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote6",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custnote7",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial958",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
