import { DropDowns } from "Helpers/functions";

export const earth = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('earth_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "earth",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ban",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "earthno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "city",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "region",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "space",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "licenseno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "licensedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "side",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "streetname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "streetcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildble",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landowner",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "beginlandvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencybeginlandguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalbeginland",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "beginlandcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencypurchaseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalpurchase",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "purchasenote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cuownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bankaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcommincomeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "usedenddate",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "owneraccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identityvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyidentityguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyvalidentity",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identitybegindate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identityenddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "crearteentryinvestment",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identityentryguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "identitynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnlandtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltncity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnregion",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnspace",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnlicense",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnside",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial036",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
