import { DropDowns } from "Helpers/functions";

export const electricitytype = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('electricitytype_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "electricitytype",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "menu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmenu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createdentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autocreatedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "incomeaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "extraaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "wateraccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "drainageaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "watervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "drainagevalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fineaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "feeaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finevalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "feevalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "calculate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "calculate2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defchecktypeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defentrytypeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial075",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
