import { DropDowns } from "Helpers/functions";

export const importmattmp = [
  {
    name: "id",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "groupcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "groupname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mattype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defunity1",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defunity2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfact2",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfix2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defunity3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfact3",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfix3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price11",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price12",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price13",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price14",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price15",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price16",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price17",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price21",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price22",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price23",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price24",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price25",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price26",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price27",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price31",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price32",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price33",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price34",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price35",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price36",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price37",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "state",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial447",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
