import { DropDowns } from "Helpers/functions";

export const landoffer = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('landoffer_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "landoffer",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customer",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "city",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "region",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "space",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "side",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "streetcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildble",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delegated",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custphone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custmobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxoffervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial598",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
