import { DropDowns } from "Helpers/functions";

export const lawsuit = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('lawsuit_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "lawsuit",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "startdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "opendate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "execdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "stopexec",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "stopexecdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "stopexecnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "stoppaydate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "quittancedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "quittanceelectricitydate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isended",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "enddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "exeno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyerrent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyerrentdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyerentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyerdebitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyercreditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lawyernote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancerent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancerentdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenanceentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancedebitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancecreditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenancenote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furniture",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furnituredate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furnitureentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furnituredebitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furniturecreditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "furniturenote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entryguid1",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entryguid2",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entryguid3",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial633",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
