import { DropDowns } from "Helpers/functions";

export const maintenancecontract = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('maintenancecontract_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "maintenancecontract",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "editdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mark",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "typeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fromdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "todate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "period",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "periodtype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "monthlyvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "paytype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trademark",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "purpose",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "whereabouts",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "incomeaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createcontractentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractfinish",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractfinishdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingamount",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingamount2",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "roundkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createresultingentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentduration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "termsofpayment",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "branchguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fineexpenceaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "newstate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnwhereabouts",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnpurpose",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnrentduration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnrentype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltntermsofpayment",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isrounded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "countoldcontract",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acquittanceprinted",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acquittanceprintdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acquittanceprintedbyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial780",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
