import { DropDowns } from "Helpers/functions";

export const maintenancecontracttype = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('maintenancecontracttype_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "maintenancecontracttype",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "menu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmenu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "incomeaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcondition",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autocreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "autopostedentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrydate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithexpencedebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithexpencecredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithdiscountdebit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "movecostwithdiscountcredit",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintreceipt",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintlogpath",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defprintacquittance",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpaynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpaynoteltn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractnoteltn",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial820",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
