import { DropDowns } from "Helpers/functions";

export const maintenanceorder = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('maintenanceorder_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "maintenanceorder",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "complaintguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maintenanceworkerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "workkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "startdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "endexpecteddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "closedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "orderstate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "reasonnotrealized",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "convertto",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "convertnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "realized",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mat",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "reason",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "repitition",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delay",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delayreason",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrydate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entryvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrycurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrycurrencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial901",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
