import { DropDowns } from "Helpers/functions";

export const mapsconfig = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('mapsconfig_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "mapsconfig",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "country",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "city",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "map1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "map2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "map3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial934",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
