import { DropDowns } from "Helpers/functions";

export const mat = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('mat_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "mat",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "code",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "barcode3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defunity",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfact2",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfact3",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfix2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unityfix3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "groupguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mattype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "avgprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lastpricedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lastprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "saleavgprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salelastpricedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salelastprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salemaxprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial957",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
