import { DropDowns } from "Helpers/functions";

export const offerprice = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('offerprice_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "offerprice",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customername",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerphone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "realtyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "price",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "priceafterdiscount",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpay",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstpaydate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "instcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "more",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insttype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "firstinsdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "oneinstallment",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lastpay",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial100",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
