import { DropDowns } from "Helpers/functions";

export const ordertype = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('ordertype_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "ordertype",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "name",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "menu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnmenu",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defstoreguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "billtypeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "changebilltype",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "changecurrency",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkstore",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkstorerecipient",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "restraintmat",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "defunity",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial185",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
