import { DropDowns } from "Helpers/functions";

export const ownerunionfee = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('ownerunionfee_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "ownerunionfee",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckflat",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckshop",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckparking",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckmovecreditcost",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ckmovedebitcost",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fee",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "roundkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "itemnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial238",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
