import { DropDowns } from "Helpers/functions";

export const parkingcontract = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('parkingcontract_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "parkingcontract",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mark",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "editdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "deliverdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "typeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isautorenewal",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "description",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentinfoguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salesmanguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatcontractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fromdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "todate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "period",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcontracttype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "monthlyvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "discountaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "paytype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "revenueaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromcustpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromcustvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromcustguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromownerpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromownervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromownerguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acincomnextyearguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromownernote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionfromcustnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromsalesmanrpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "commissionfromsalesmanvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "acsalesmancommissionguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accommissionexpenseguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salesmancommnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee1",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount1guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee2",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount2guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee3",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount3guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee4",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount4guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfee5",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherfeeaccount5guid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractfinish",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractfinishdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "editcontractfinishdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingamount",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingamount2",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resultingnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fine",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "fineaccount",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finenote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createresultingentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insurancevalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "insurancevalueold",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcontractprice",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "certificatvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountcertificatvalue",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentduration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "termsofpayment",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "step1complete",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "step2complete",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "step3complete",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "step4complete",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "step5complete",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "certification",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "branchguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cardno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "carno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "cartype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "carcolor",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "emirate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createcontractentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finerevenueaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "newstate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3date1",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license3date2",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnrentduration",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnrentype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltntermsofpayment",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isrounded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "judicial",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isreturninsurance",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "returninsurancedate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "prvcontractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "addpercent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "addvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial280",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
