import { DropDowns } from "Helpers/functions";

export const pricing = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('pricing_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "pricing",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "repno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "repdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "regno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "attachment",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ownername",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "issueside",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "docno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "docdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "country",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "region",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "city",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "quarter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "street",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "designname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pieceno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "realtynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "regionstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "building",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pubutil1",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pubutil2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pubutil3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "service1",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "service2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "service3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "service4",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "regionnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "areastate1",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "areastate2",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "areastate3",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildsys",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parambuild",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "regionclass",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "dimension1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "dimension2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "dimension3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "dimension4",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "boundary1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "boundary2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "boundary3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "boundary4",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "dimensionnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "coordinate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "resume",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "merit",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "drawback",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "projecteffect",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "realtyvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "meterprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currentlandprice",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pricingway",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pricingvalue",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxprice",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "minprice",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "estimationvalue",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "estimationnote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mappath1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mappath2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mappath3",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "createentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrydate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entryvalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrycurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrycurrencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditaccountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debitcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "creditcostguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "entrynote",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial378",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
