import { DropDowns } from "Helpers/functions";

export const realty_users = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('realty_users_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "realty_users",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "loginname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "password",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "badmin",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userseclvl",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "branchguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial518",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
