import { DropDowns } from "Helpers/functions";

export const reminder = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('reminder_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "reminder",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "subject",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "reminddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finished",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "foralluser",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial626",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
