import { DropDowns } from "Helpers/functions";

export const secondary_entry = [
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "secondary_entry",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "typeguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "number",
    type: "integer",
    default_value: "nextval('secondary_entry_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "mark",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "kind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "accountguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "date",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "currencyval",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "branchguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salesmanguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "contractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "checkcreateentry",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "isrounded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "receiptno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "debit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "credit",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "itemcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial727",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
