import { DropDowns } from "Helpers/functions";

export const shop = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('shop_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "shop",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "no",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "judicial",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ban",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "buildingguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unity",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shopkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "description",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "overlooking",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "unifiednum",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "manservantroom",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "driverroom",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costprice",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costcurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rent",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "rentcurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "sale",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "salecurrencyguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "note",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "costguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "flatowner",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerstate",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offertype",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "restrained",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "restraineduserguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "watercounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "electricitycounter",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnshopkind",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltndescription",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "ltnoverlooking",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "class",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondtype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bondno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bonddate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license1",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "license2",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lastcontractguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial819",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
