import { DropDowns } from "Helpers/functions";

export const tblshortcut = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('tblshortcut_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "tblshortcut",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "itemname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "itemindex",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "kind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "text",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "shortcut",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "userguid",
    type: "uuid",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial025",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
