import { DropDowns } from "Helpers/functions";

export const villaoffer = [
  {
    name: "number",
    type: "integer",
    default_value: "nextval('villaoffer_number_seq1'::regclass)",
    required: true,
    hide_in: "",
  },
  {
    name: "guid",
    type: "uuid",
    default_value: null,
    required: true,
    is_ref: true,
    ref_table: "villaoffer",
    ref_col: "guid",
    ref_name: "",
    hide_in: "",
  },
  {
    name: "seclvl",
    key: "select",
    list: DropDowns("seclvl"),
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "watercounter",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "electricitycounter",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "complexname",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "emirate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "area",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "street",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "suburb",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "pieceno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "basinno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "villano",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "doctype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "docno",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "docdate",
    type: "date",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "customer",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "address",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offerkind",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "offervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "floorcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "balconycount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "roomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "otherroomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "serviceroomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "bathroomcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "stairsinternal",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "roomstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "landareabuilding",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "finishingstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "securitytype",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "securitysystem",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "wall",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "wallstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "lightingcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "parkingshaded",
    type: "boolean",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "poolcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "poolstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "poolsystem",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "playgroundcount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "playgroundarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "gardencount",
    type: "integer",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "gardenarea",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "gardenstate",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "details",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "delegated",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custphone",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "custmobile",
    type: "character varying",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "maxoffervalue",
    type: "double precision",
    default_value: null,
    required: false,
    hide_in: "",
  },
  {
    name: "trial263",
    type: "character",
    default_value: null,
    required: false,
    hide_in: "",
  },
];
